import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { LoadingProvider } from "@/context/LoadingContext";
import LoadingOverlay from "@/components/LoadingOverlay";


import AuthProvider from "@/components/AuthProvider/AuthProvider"
import { StreamVideoProvider } from "@/providers/StreamClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <LoadingProvider>
          <LoadingOverlay />
          <AuthProvider>
            <StreamVideoProvider>
              {children}
              </StreamVideoProvider>
          </AuthProvider>
        </LoadingProvider>

      </body>
    </html>
  );
}
